### PR TITLE
explicitly check if view_func.view_class is MethodViewType in add_url_rule

### LINKED ISSUE #379: KeyError when using add_url_for with flask View
## context

[flask-graphql](https://github.com/graphql-python/flask-graphql) is a project that adds graphql support to flask applications. 

apiflask produces an error when using `add_url_for` with view_func=`GraphQLView.as_view(...)`.

## steps to reproduce 

1. setup a minimal apiflask application that uses flask-graphql
```
#requirements.txt 
apiflask 
flask-graphql
``` 
```python
# app.py
from apiflask import APIFlask
from flask_graphql import GraphQLView
from graphql.type.schema import GraphQLSchema
from graphql.type.scalars import GraphQLString
from graphql.type.definition import (GraphQLField, GraphQLObjectType)

app = APIFlask(__name__)

# setup basic graphql schema 
query = PersonType = GraphQLObjectType('Person', {
        'name': GraphQLField(GraphQLString),
    })

schema = GraphQLSchema(query=query)

app.add_url_rule('/graphql', view_func=GraphQLView.as_view(
    'graphql',
    schema=schema,
    graphiql=True,
))
```

2. Run the flask app 
```python -m flask run```

3. Visit the AP documentation at `http://localhost:5000/docs:`

## Expected Result: 
Either the '/graphql' endpoint is ignored, or docs are generated for the endpoint. 

## Actual Results: 
`KeyError: 'get'`

Truncated Stacktrace: 
```bash
  File "...\venv\lib\site-packages\apiflask\route.py", line 39, in record_spec_for_view_class
    method = view_class.__dict__[method_name.lower()]
KeyError: 'get'
```

Environment:

- Python version: 3.9.13
- Flask version: 2.1.3
- APIFlask version: 1.1.3

## proposed solution 
From my understanding, apiflask has support for flask `MethodView`. This seems to be implemented in `route.py`.  

`GraphQLView` is a `View` not a `MethodView`. 

This error seems to be caused by apiflask treating the `GraphQLView` like it is a `MethodView`. 

If this is the issue, then maybe `add_url_rule` in route.py could check if a class is a `View` and  skip it.

### PR DESCRIPTION
**Pull request by rod7760**
* fixes #379 

Checklist:

- [X] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the `docs` folder and in code docstring.
- [X] Add an entry in `CHANGES.md` summarizing the change and linking to the issue and your username.
- [ ] Add `*Version changed*` or `*Version added*` note in any relevant docs and docstring.
- [X] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by rod7760** [comment]
everything is passing except style, but that is failing on main also. 
https://github.com/apiflask/apiflask/actions/runs/3655663131/jobs/6177240580

**Comment by rod7760** [comment]
Is `Add *Version changed* or *Version added* note in any relevant docs and docstring.` relevant in this PR?

**Comment by rod7760** [comment]
My tests are currently failing because app.py does this 

```
# add a default 200 response for bare views
            if not hasattr(view_func, '_spec'):
                if self.config['AUTO_200_RESPONSE']:
```

I am going to explicitly set hide=True for flask Views to avoid this.

**Comment by rod7760** [comment]
Ok, this should actually be ready for review now.

It is a bit hacky to set `view_func._spec = {'hide': True}`, but I wasn't sure how else to get around the auto 200 responses being added to bare views.

**Comment by greyli** [comment]
Thanks! I will fix the style check later.

**Pull request merged**
