### PR TITLE
Correct err in docs and add example application for file uploading

### PR DESCRIPTION
**Pull request by uncle-lv**
The keyword argument of `form_and_files` should be `form_and_files_data`.

### CODE REVIEW

**Comment by uncle-lv** [comment]
Added a file upload example #262

**Comment by greyli** [comment]
Please also update the [README.md](https://github.com/apiflask/apiflask/blob/main/examples/README.md) in the examples folder to include the new example.

**Comment by uncle-lv** [comment]
> Please also update the [README.md](https://github.com/apiflask/apiflask/blob/main/examples/README.md) in the examples folder to include the new example.

Done it!

**Comment by greyli** [comment]
Merged, thanks!

**Pull request merged**
